version: "3"

services:
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - data-volume:/var/lib/backend
  backend:
    env_file: ./backend/.env
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - data-volume:/var/lib/backend
    expose:
      - 8000
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "1337:1337"
    volumes:
      - data-volume:/var/lib/backend
    depends_on:
      - backend
volumes:
  data-volume:
